##############################
# Stage 1: Build environment
##############################
FROM ubuntu:18.04 AS builder

RUN apt-get update && \
    apt-get install -y openjdk-8-jdk wget && \
    rm -rf /var/lib/apt/lists/*

ENV TOMCAT_VERSION=8.5.55

RUN wget https://archive.apache.org/dist/tomcat/tomcat-8/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz -O /tmp/tomcat.tar.gz && \
    tar -xvf /tmp/tomcat.tar.gz -C /tmp && \
    mv /tmp/apache-tomcat-${TOMCAT_VERSION} /tmp/tomcat

RUN rm -rf /tmp/tomcat/webapps/*

COPY sampleapp.war /tmp/tomcat/webapps/


##############################
# Stage 2: Slim runtime image
##############################
FROM eclipse-temurin:8-jre

COPY --from=builder /tmp/tomcat /opt/tomcat

RUN chmod +x /opt/tomcat/bin/*.sh

EXPOSE 8080

CMD ["/opt/tomcat/bin/catalina.sh", "run"]
