apiVersion: v1
kind: Pod
metadata:
  name: secure-app
  namespace: web-apps      # FIX: Explicit namespace
spec:
  containers:
  - name: nginx
    image: nginx:latest
    securityContext:
      privileged: false            # FIX: Disable Privileged mode
      runAsNonRoot: true           # FIX: Block Root user
      readOnlyRootFilesystem: true # FIX: Prevent file tampering